### ISSUE TITLE
请问 这个web app 所使用到什么技术，可否指教一下

### ISSUE THREAD

**Issue by galihuotui** [airingursb/bilibili-report#1]

**Comment by airingursb** [comment]
主要有：
1. jQuery
2. fullPage.js
3. Canvas
4. CSS3

**Comment by galihuotui** [comment]
提供数据 的 服务端返回 json 吗

**Comment by airingursb** [comment]
@cuikangyuan 

项目数据是已经分析过了，所以这个页面是静态的。

数据是用用户爬虫（[bilibili-user](https://github.com/airingursb/bilibili-user)）抓取的，然后用R对这些数据进行了简单的[统计分析](http://ursb.me/2016/02/23/B%E7%AB%992000%E4%B8%87%E7%94%A8%E6%88%B7%E5%88%86%E6%9E%90/)。

**Comment by galihuotui** [comment]
哦哦 谢谢

**Comment by airingursb** [comment]
@cuikangyuan 不客气 : )
