### ISSUE TITLE
关于活跃用户

### ISSUE THREAD

**Issue by ghost** [airingursb/bilibili-report#2]
活跃用户40%是如何判断的

**Comment by airingursb** [comment]
@airlbk 由于B站有经验等级规则，用户的活跃度可以依据等级判断。
等级为0，就是只注册未登陆过的用户。等级为1或2，为非活跃用户。等级为3以上，基本上可判断就是活跃用户。其中等级为5或6的，为投稿数特别特别多、视频特别火爆的用户，为B站的主干用户（约5000人）。

这里的40%的“活跃用户”有点不准确，因为这里有60%的用户可判断出是“机器人”，剩下的40%应该是属于正常用户。真正达到Lv3以上的只有11%的用户。

**Comment by ghost** [comment]
谢谢

**Comment by airlbk** [comment]
谢谢
